export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const EDIT_CART_REQUEST = 'EDIT_CART_REQUEST'
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS'
export const EDIT_CART_FAIL = 'EDIT_CART_FAIL'

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL'

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST'
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS'
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL'