export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'
export const ADD_ORDER_RESET = 'ADD_ORDER_RESET'

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'

export const GET_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'

export const GET_ORDER_REQUEST = 'GET_ALL_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ALL_ORDER_FAIL'