export const EDIT_SEARCH_REQUEST = 'EDIT_SEARCH_REQUEST'
export const EDIT_SEARCH_SUCCESS = 'EDIT_SEARCH_SUCCESS'
export const EDIT_SEARCH_FAIL = 'EDIT_SEARCH_FAIL'
export const EDIT_SEARCH = 'EDIT_SEARCH'
