export const ADD_NEW_SHIPPING_REQUEST = 'ADD_NEW_SHIPPING_REQUEST'
export const ADD_NEW_SHIPPING_FAIL = 'ADD_NEW_SHIPPING_FAIL'
export const ADD_NEW_SHIPPING_SUCCESS = 'ADD_NEW_SHIPPING_SUCCESS'

export const DELETE_SHIPPING_REQUEST = 'DELETE_SHIPPING_REQUEST'
export const DELETE_SHIPPING_FAIL = 'DELETE_SHIPPING_FAIL'
export const DELETE_SHIPPING_SUCCESS = 'DELETE_SHIPPING_SUCCESS'
